name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install build deps
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential nasm xorriso grub-pc-bin qemu-system-x86

      - name: Make help (sanity)
        run: make help || true

      - name: Smoke test (headless QEMU)
        run: |
          chmod +x scripts/qemu-smoke.sh
          ./scripts/qemu-smoke.sh
